var dataUrl = 'data/gardens.csv';
var maxZoom = 22;
var fieldSeparator = ',';
var baseUrl = 'http://otile{s}.mqcdn.com/tiles/1.0.0/osm/{z}/{x}/{y}.jpg';
var baseAttribution = 'Data, imagery and map information provided by <a href="http://open.mapquest.co.uk" target="_blank">MapQuest</a>, <a href="http://www.openstreetmap.org/" target="_blank">OpenStreetMap</a> and contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/" target="_blank">CC-BY-SA</a>';
var subdomains = '1234';
var clusterOptions = {showCoverageOnHover: false, maxClusterRadius: 50};
var labelColumn = "Title";
var opacity = 1.0;
//var jsonUrl = 'https://spreadsheets.google.com/feeds/list/13wjQS8ZfO7rA30p16btGJEaGitxJBjJMCLMYirhH8RA/od6/public/basic?alt=json';